$(window).scroll(function () {
    $('.triangle1').css({'left': 88 + ($(window).scrollTop() / 15)});
    $('.triangle2').css({'left': 540 + ($(window).scrollTop() / 15)});
    $('.triangle3').css({'right': 200 - ($(window).scrollTop() / 15)});
    $('.triangle3').css({'top': 1050 + ($(window).scrollTop() / 15)});
    $('.triangle4').css({'right': 700 + ($(window).scrollTop() / 15)});
    $('.triangle5').css({'left': 194 - ($(window).scrollTop() / 15)});
    $('.triangle5').css({'top': 1987 + ($(window).scrollTop() / 15)});
    $('.triangle6').css({'right': 214 + ($(window).scrollTop() / 15)});
    $('.triangle7').css({'left': 100 - ($(window).scrollTop() / 15)});
    $('.triangle8').css({'right': 54 - ($(window).scrollTop() / 15)});
    $('.triangle8').css({'top': 3650 + ($(window).scrollTop() / 15)});
    $('.circle1').css({'right': 778 - ($(window).scrollTop() / 15)});
    $('.circle1').css({'top': 952 + ($(window).scrollTop() / 15)});
    $('.circle2').css({'left': 729 - ($(window).scrollTop() / 15)});
    $('.circle3').css({'right': 431 + ($(window).scrollTop() / 15)});
    $('.circle3').css({'top': 2265 + ($(window).scrollTop() / 15)});
    $('.circle4').css({'left': 300 - ($(window).scrollTop() / 15)});
    $('.circle5').css({'right': ($(window).scrollTop() / 15)});
    $('.circle5').css({'bottom': 539 + ($(window).scrollTop() / 15)});
    $('.circle6').css({'right': 880 + ($(window).scrollTop() / 15)});
    $('.circle6').css({'bottom': 89 + ($(window).scrollTop() / 15)});
    $('.circle7').css({'right': 600 - ($(window).scrollTop() / 15)});
    $('.square1').css({'left': 250 - ($(window).scrollTop() / 15)});
    $('.square2').css({'right': 400 + ($(window).scrollTop() / 15)});
    $('.square3').css({'left': 665 + ($(window).scrollTop() / 15)});
    $('.square4').css({'right': 670 + ($(window).scrollTop() / 15)});
    $('.square4').css({'top': 1608 - ($(window).scrollTop() / 15)});
    $('.square5').css({'left': 300 + ($(window).scrollTop() / 15)});
    $('.square6').css({'left': 136 + ($(window).scrollTop() / 15)});
    $('.square7').css({'left': 10 + ($(window).scrollTop() / 15)});
    $('.square8').css({'right': 50 + ($(window).scrollTop() / 15)});
});